### ISSUE TITLE
Graphs not present in Chrome version "50.0.2661.102 m"

### ISSUE THREAD

**Issue by jahopki** [Thomas-S-B/visualee#5]
In the listed version of Chrome, graphs are not visible; in Firefox version 27.0.1, the graphs appear just fine.  I assume it's a conflict with the version of jquery included with the project.  I'm currently using version 0.28 of visualee -- and it's a *REALLY* helpful utility!

**Comment by jahopki** [comment]
it seems that Chrome is more safe than Firefox...  After shutting down all running instances of Chrome and then starting it again with the " --allow-file-access-from-files" parameter, the graphs were able to load properly without changing any of the referenced stylesheets or javascript libs.

**Comment by Thomas-S-B** [comment]
I'm sorry that I'm answering that late - i was on vacation.
I really appreciate, that you are enjoying visualee.
