### ISSUE TITLE
License for the code?

### ISSUE THREAD

**Issue by OndrejM** [Thomas-S-B/visualee#6]
Hi, is the source code distributed under Apache license? I see that the license appears in the pom.xml, but can you also create a LICENSE file to make this more explicit?

**Comment by Thomas-S-B** [comment]
Hi,
shortly: i will add it asap - sorry about that,  but i'm always really busy before x-mas (as every year :-) ).

Cheers,
Thomas

**Comment by Thomas-S-B** [comment]
Hi,
added the Apache 2.0 LICENSE.

Cheers
Thomas
